name: Build dist from ZIP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tools
        run: sudo apt-get update && sudo apt-get install -y unzip zip

      - name: Find and unzip source ZIP
        shell: bash
        run: |
          ZIP_FILE=$(ls *.zip | head -n1)
          echo "Using ZIP: $ZIP_FILE"
          mkdir srczip
          unzip -q "$ZIP_FILE" -d srczip
          shopt -s dotglob
          mv srczip/* .
          rmdir srczip

      - name: Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Pack dist.zip
        run: |
          cd dist
          zip -r ../dist.zip .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip
          
